# Переменные, применимые ко всем дистрибутивам одинаково:

jenkins_image: jenkins/jenkins:lts-jdk11
jenkins_data_dir: /opt/jenkins_data
jenkins_config_dir: /opt/jenkins_config
jenkins_check_docker: docker --version
jenkins_file_compose: jenkins-docker-compose.yaml
jenkins_file_mode: "u=rw,g=r,o=r"
jenkins_file_owner: "1000"
jenkins_file_group: "1000"

# Переменные для конфигурации Jenkins на OpenSUSE:

# Переменные для конфигурации Jenkins на CentOS:

# Переменные для конфигурации Jenkins на Ubuntu:
