---
  # Установка пакета Nginx на дистрибутиве OpenSUSE.
  - name: Installing required packages on OpenSUSE
    zypper: 
      name: "{{ nginx_package }}"
      state: present
      update_cache: yes

  # Запуск сервиса nginx.service на дистрибутиве OpenSUSE.
  - name: Start Nginx service on OpenSUSE
    systemd:
      name: nginx
      state: started
      enabled: yes
    ignore_errors: true

  # Передача конфигурационного файла Nginx для проксирования, при обращении к сайту Jenkins на дистрибутиве OpenSUSE.
  - name: Copy nginx config for Jenkins site on OpenSUSE
    template:
      src: templates/jenkins-nginx-ssl.conf.j2
      dest: "/etc/nginx/conf.d/{{ jenkins_nginx_domain }}.conf"
      mode: "{{ nginx_file_mode }}"
      owner: "{{ nginx_file_owner }}"
      group: "{{ nginx_file_group }}"
    notify: restart nginx

  # Выполнение команды nginx -t после добавления конфигурационного файла на дистрибутиве OpenSUSE.
  - name: Output of command nginx -t after changes
    shell: nginx -t
    register: command_output
    ignore_errors: true
  - debug: msg="{{ command_output.stderr }}"
