---
# Вызов нескольких ролей по установке Nginx + SSL на удаленном узле, для проксирования запросов при обращении к Jenkins.
- name: Configuring Nginx + SSL on remote host
  gather_facts: yes
  become: yes
  hosts: 
    - all
  roles:
    - certbot
    - nginx
