# Переменные, применимые ко всем дистрибутивам одинаково:

nginx_file_mode: "u=rw,g=r,o=r"
nginx_file_owner: "0"
nginx_file_group: "0"

# Переменные для настройки Nginx на OpenSUSE:

# Переменные для настройки Nginx на Centos 8:

# Переменные для настройки Nginx на Ubuntu:
