---
  # Выполнение хендлера, который вызывается при изменении конфигурационных файлов, во время выполнения роли nginx.
  - name: restart nginx
    service:
      name: nginx
      state: restarted
    ignore_errors: true
