---
  # # Проверка того, необходимо ли запустить роль Docker на дистрибутиве OpenSUSE.
  # - name: Check if Docker is installed on OpenSUSE
  #   command: "{{ jenkins_check_docker }}"
  #   register: docker_check
  #   ignore_errors: true
  #   tags: suse

  # # Вызов роли Docker для установки, со всеми необходимыми компонентами, для последующего запуска Jenkins на дистрибутиве OpenSUSE.
  # - name: Installing Docker on OpenSUSE before Jenkins
  #   include_role:
  #     name: docker
  #     tasks_from: suse.yaml
  #   when:
  #     - docker_check.msg is defined
  #   tags: suse

  # Создание директории для хранения данных и конфигурации Jenkins.
  - name: Create Jenkins directory on OpenSUSE
    file:
      state: directory
      path: "{{ item.path }}"
      mode: "{{ jenkins_file_mode }}"
      owner: "{{ jenkins_file_owner }}"
      group: "{{ jenkins_file_group }}"
    with_items:
      - { path: "{{ jenkins_data_dir }}" }
      - { path: "{{ jenkins_config_dir }}" }
    tags: suse

  # Копирование файлов из директории ./roles/jenkins/files и их последующая передача в директорию jenkins_config.
  - name: Copy docker files in directory jenkins_config on OpenSUSE
    copy:
      src: files/
      dest: "{{ jenkins_config_dir }}"
      mode: "{{ jenkins_file_mode }}"
      owner: "{{ jenkins_file_owner }}"
      group: "{{ jenkins_file_group }}"
    tags: suse

  # Копирование файлов из директории ./roles/jenkins/templates и их последующая передача в директорию jenkins_config.
  - name: Copy template jenkins.yaml in directory jenkins_config on OpenSUSE
    template:
      src: templates/jenkins.yaml
      dest: "{{ jenkins_config_dir }}/jenkins.yaml"
      mode: "{{ jenkins_file_mode }}"
      owner: "{{ jenkins_file_owner }}"
      group: "{{ jenkins_file_group }}"
    tags: suse

  # Пул образа Jenkins с Docker Hub на удаленном хосте.
  - name: Pull the Jenkins docker image on OpenSUSE from Docker Hub
    docker_image:
      name: "{{ jenkins_image }}"
    tags: suse

  # Запуск Docker-compose на удаленном хосте.
  - name: Run Jenkins via docker-compose on OpenSUSE
    docker_compose:
      build: yes
      files: "{{ jenkins_file_compose }}"
      project_src: "{{ jenkins_config_dir }}"
      recreate: always
    register: output
  - debug:
      var: output
    tags: suse

  # Опциональные задачи: Дело в том, что при каждом прогоне через Ansible создается новый образ (если были изменения в Dockerfile), при этом старые не удаляются сами по себе.
  # Задачи, описанные ниже, решают данную проблему. Это было нужно мне, пока я занимался отладкой, но не факт, что понадобится вам.

  # - name: Get details of all images on OpenSUSE
  #   docker_host_info:
  #     images: yes
  #     verbose_output: yes
  #   register: image_info
  #   tags: suse

  # - name: Remove all unused images on OpenSUSE
  #   docker_image:
  #     name: "{{ item }}"
  #     state: absent
  #   with_items: "{{ image_info.images | map(attribute='Id') | list }}"
  #   ignore_errors: true
  #   tags: suse
