---
  # Обновление всех пакетов на дистрибутиве OpenSUSE.
  - name: Update all packages on OpenSUSE
    zypper:
      name: '*'
      state: latest
      update_cache: yes
    tags: package

  # Установка пакетов rpm из списка необходимых, которые определены в виде переменной в директории defaults.
  - name: Installing required packages on OpenSUSE
    zypper: 
      name: "{{ opensuse_packages_list }}"
      state: latest
      update_cache: yes
    tags: package

  # Установка пакетов pip из списка необходимых, которые определены в виде переменной в директории defaults.
  - name: Installing required package for pip on OpenSUSE
    pip:
      name: "{{ opensuse_pip_list }}"
    tags: package
